import { IAgroProduct } from "@/interface/types"

export const productsToPreLoad: IAgroProduct[] = [
  {
    id: 1,
    images:[ "https://cdn.usegalileo.ai/sdxl10/efc9218c-9049-4496-8555-512cbbe0ed74.png"  ],
    name: "Espinaca",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 2,
    images: ["https://cdn.usegalileo.ai/sdxl10/44fb0323-1367-45a5-b1fa-bbf923124e56.png"],
    name: "Col Organica",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 3,
    images: ["https://cdn.usegalileo.ai/sdxl10/d0efad32-3aa0-4047-a6c6-6e413f5ce13a.png"],
    name: "Tomate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 4,
    images: ["https://cdn.usegalileo.ai/sdxl10/7113b78e-9220-4c3e-b69e-503fd2f70482.png"],
    name: "Zanahoria",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 5,
    images: ["https://cdn.usegalileo.ai/sdxl10/4e888dd2-9166-4885-b582-0eda25665981.png"],
    name: "Zanahoria",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 6,
    images: ["https://cdn.usegalileo.ai/sdxl10/fda5c103-de76-4d6c-b2aa-8737a697424c.png"],
    name: "Tomate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 7,
    images: ["https://cdn.usegalileo.ai/sdxl10/5ab02c52-c298-4f97-a266-4940bde454e4.png"],
    name: "col organica",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
  {
    id: 8,
    images: ["https://cdn.usegalileo.ai/sdxl10/d0efad32-3aa0-4047-a6c6-6e413f5ce13a.png"],
    name: "Tomate",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pricePerUnit: 100.99,
    variety: "",
    origin: "",
    harvestDate: "",
    unitType: "",
    stock: "",
    nutritionalInfo: {
      calories: 20,
      protein: 1,
      fat: 0.2,
      carbs: 3,
    },
    uses: ["Ensaladas", "Salsas", "Guisos"],
    certifications: "Orgánico, Fair Trade",
    shippingOptions: {
      method: "Refrigerated",
      deliveryTime: "15-20 días",
      seaFreight: "Marsk",
    },
    reviews: [
      {
        userName: "Juan Pérez",
        rating: 5,
        comment: "Producto muy fresco y de excelente calidad.",
      },
    ],
  },
]