name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/srv-csdfe1l6l47c73dad1i0?key=TjeWMUi4oNE"
